version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: [InvoiceProcessingService]

  api:
    build:
      context: .
      dockerfile: src/InvoiceService/InvoiceService.API/Dockerfile
    container_name: invoice-api
    depends_on:
      - rabbitmq
    ports:
      - "5169:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__InvoicesDb: "Data Source=/app/data/invoices.db;Cache=Shared"
      MongoDb__ConnectionString: "mongodb://root:example@mongodb:27017"
      MongoDb__DatabaseName: "InvoiceReadDb"
      CLOUDAMQP_URL: ${CLOUDAMQP_URL:-}
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
      Swagger__Enabled: "true"

      # JWT
      Jwt__Issuer: "InvoiceProcessingService"
      Jwt__Audience: "InvoiceProcessingService.Clients"
      Jwt__Key: "super-secret-jwt-key-only-for-demo-and-created-by-majid"
      Jwt__ExpiryMinutes: "60"
    volumes:
      - invoices-data:/app/data
    networks: [InvoiceProcessingService]

  subscriber:
    build:
      context: .
      dockerfile: src/Subscriber/InvoiceSubscriber.Console/Dockerfile
    container_name: invoice-subscriber
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ConnectionStrings__InboxDb: "Data Source=/app/data/inbox.db;Cache=Shared"
      MongoDb__ConnectionString: "mongodb://root:example@mongodb:27017"
      MongoDb__DatabaseName: "InvoiceReadDb"
      CLOUDAMQP_URL: ${CLOUDAMQP_URL:-}
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
    volumes:
      - subscriber-inbox:/app/data
    networks: [InvoiceProcessingService]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: [InvoiceProcessingService]

networks:
  InvoiceProcessingService:
    driver: bridge

volumes:
  invoices-data:
  subscriber-inbox:
  mongo-data: