version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@@SQLSERVER_SA_PASSWORD@@
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=@@RABBITMQ_USERNAME@@
      - RABBITMQ_DEFAULT_PASS=@@RABBITMQ_PASSWORD@@
    restart: always

  orderservice:
    image: majidebadiparsajob/orderservice:latest
    ports:
      - "5000:80"
    restart: always
    environment:
      - ConnectionStrings__OrderDb=@@ORDERDB_CONNECTIONSTRING@@
      - RabbitMq__Host=@@RABBITMQ_HOST@@
      - RabbitMq__VirtualHost=@@RABBITMQ_VIRTUALHOST@@
      - RabbitMq__Username=@@RABBITMQ_USERNAME@@
      - RabbitMq__Password=@@RABBITMQ_PASSWORD@@

  inventoryservice:
    image: majidebadiparsajob/inventoryservice:latest
    ports:
      - "5001:80"
    restart: always
    environment:
      - ConnectionStrings__InventoryDb=@@INVENTORYDB_CONNECTIONSTRING@@
      - RabbitMq__Host=@@RABBITMQ_HOST@@
      - RabbitMq__VirtualHost=@@RABBITMQ_VIRTUALHOST@@
      - RabbitMq__Username=@@RABBITMQ_USERNAME@@
      - RabbitMq__Password=@@RABBITMQ_PASSWORD@@