version: '3.8'

services:

  orderservice:
    image: majidebadiparsajob/orderservice:latest
    ports:
      - "5004:80"
    restart: always
    environment:
      - ConnectionStrings__OrderDb=@@ORDERDB_CONNECTIONSTRING@@
      - RabbitMq__Host=@@RABBITMQ_HOST@@
      - RabbitMq__VirtualHost=@@RABBITMQ_VIRTUALHOST@@
      - RabbitMq__Username=@@RABBITMQ_USERNAME@@
      - RabbitMq__Password=@@RABBITMQ_PASSWORD@@

  inventoryservice:
    image: majidebadiparsajob/inventoryservice:latest
    ports:
      - "5005:80"
    restart: always
    environment:
      - ConnectionStrings__InventoryDb=@@INVENTORYDB_CONNECTIONSTRING@@
      - RabbitMq__Host=@@RABBITMQ_HOST@@
      - RabbitMq__VirtualHost=@@RABBITMQ_VIRTUALHOST@@
      - RabbitMq__Username=@@RABBITMQ_USERNAME@@
      - RabbitMq__Password=@@RABBITMQ_PASSWORD@@
