version: '3.8'

services:

  orderservice:
    image: majidebadiparsajob/orderservice:latest
    ports:
      - "5000:80"
    restart: always

  inventoryservice:
    image: majidebadiparsajob/inventoryservice:latest
    ports:
      - "5001:80"
    restart: always
