name: EShop CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  # Build & Test OrderService
  build-and-test-order:
    name: Build & Test OrderService
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "eSh@pDem@1"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P eSh@pDem@1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies - OrderService
      run: dotnet restore ./OrderService/OrderService.API/OrderService.API.csproj

    - name: Build - OrderService
      run: dotnet build ./OrderService/OrderService.API/OrderService.API.csproj --no-restore --configuration Release

    - name: Test - OrderService
      run: dotnet test ./OrderService/OrderService.Tests/OrderService.Tests.csproj --no-build --verbosity normal

  # Build & Test InventoryService
  build-and-test-inventory:
    name: Build & Test InventoryService
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies - InventoryService
      run: dotnet restore ./InventoryService/InventoryService.API/InventoryService.API.csproj

    - name: Build - InventoryService
      run: dotnet build ./InventoryService/InventoryService.API/InventoryService.API.csproj --no-restore --configuration Release

    - name: Test - InventoryService
      run: dotnet test ./InventoryService/InventoryService.Tests/InventoryService.Tests.csproj --no-build --verbosity normal