name: DeliveryService - Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-prod-url

    steps:
      - uses: actions/checkout@v4

      - name: Download EF bundle
        uses: actions/download-artifact@v4
        with:
          name: deliveryservice-migrations-bundle
          path: ./artifacts/deliveryservice

      - name: Create .env for prod
        run: |
          cat > .env <<EOF
          SQLSERVER_SA_PASSWORD=${{ secrets.PROD_SQLSERVER_SA_PASSWORD }}
          ORDERDB_CONNECTIONSTRING=${{ secrets.PROD_ORDERDB_CONNECTIONSTRING }}
          INVENTORYDB_CONNECTIONSTRING=${{ secrets.PROD_INVENTORYDB_CONNECTIONSTRING }}
          DELIVERYDB_CONNECTIONSTRING=${{ secrets.PROD_DELIVERYDB_CONNECTIONSTRING }}
          RABBITMQ_USERNAME=${{ secrets.PROD_RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD=${{ secrets.PROD_RABBITMQ_PASSWORD }}
          RABBITMQ_VIRTUALHOST=${{ secrets.PROD_RABBITMQ_VIRTUALHOST }}
          RABBITMQ_ORDERRECEIVEENDPOINT=${{ secrets.PROD_RABBITMQ_ORDERRECEIVEENDPOINT }}
          RABBITMQ_INVENTORYRECEIVEENDPOINT=${{ secrets.PROD_RABBITMQ_INVENTORYRECEIVEENDPOINT }}
          RABBITMQ_DELIVERYRECEIVEENDPOINT=${{ secrets.PROD_RABBITMQ_DELIVERYRECEIVEENDPOINT }}
          ORDERSERVICE_IMAGE=majidebadiparsajob/orderservice:sha-${{ github.sha::7 }}
          INVENTORYSERVICE_IMAGE=majidebadiparsajob/inventoryservice:sha-<LAST_GOOD_SHA>
          DELIVERYSERVICE_IMAGE=majidebadiparsajob/deliveryservice:sha-<LAST_GOOD_SHA>
          EOF

      - name: Run EF bundle (Delivery DB - prod)
        env:
          ConnectionStrings__DeliveryDb: ${{ secrets.PROD_DELIVERYDB_CONNECTIONSTRING }}
        run: |
          chmod +x ./artifacts/deliveryservice/deliveryservice-migrations
          ./artifacts/deliveryservice/deliveryservice-migrations

      - name: Compose Up (prod)
        run: |
          docker network inspect eshop_eshopnetwork >/dev/null 2>&1 || docker network create eshop_eshopnetwork
          docker compose --env-file .env -f deploy/docker-compose.production.yml pull
          docker compose --env-file .env -f deploy/docker-compose.production.yml up -d deliveryservice
