name: Deploy to Dev (Local Self-Hosted Runner)

on:
  workflow_run:
    workflows: ["Docker Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest OrderService image
      run: docker pull majidebadiparsajob/orderservice:latest

    - name: Pull latest InventoryService image
      run: docker pull majidebadiparsajob/inventoryservice:latest

    - name: Deploy using docker-compose
      run: docker-compose -f deploy/docker-compose.dev.yml up -d
