name: Deploy to Dev

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-dev:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest images
        run: |
          docker pull majidebadiparsajob/orderservice:latest
          docker pull majidebadiparsajob/inventoryservice:latest

      - name: Clean previous containers
        run: docker-compose -f deploy/docker-compose.dev.yml down
        continue-on-error: true

      - name: Deploy using docker-compose
        run: docker-compose -f deploy/docker-compose.dev.yml up -d
