name: Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Staging
          - Production

jobs:
  deploy:
    runs-on: self-hosted

    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest OrderService image
      run: docker pull majidebadiparsajob/orderservice:latest

    - name: Pull latest InventoryService image
      run: docker pull majidebadiparsajob/inventoryservice:latest

    - name: Clean previous containers
      run: docker-compose -f deploy/docker-compose.dev.yml down
      continue-on-error: true

    - name: Deploy using docker-compose
      run: docker-compose -f deploy/docker-compose.dev.yml up -d
