name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: self-hosted

    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest images
        run: |
          docker pull majidebadiparsajob/orderservice:latest
          docker pull majidebadiparsajob/inventoryservice:latest

      - name: Clean previous containers
        run: docker-compose -f deploy/docker-compose.staging.yml down
        continue-on-error: true

      - name: Deploy using docker-compose
        run: docker-compose -f deploy/docker-compose.staging.yml up -d
