name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: dev

    env:
      SQLSERVER_SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}
      ORDERDB_CONNECTIONSTRING: ${{ secrets.ORDERDB_CONNECTIONSTRING }}
      INVENTORYDB_CONNECTIONSTRING: ${{ secrets.INVENTORYDB_CONNECTIONSTRING }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_VIRTUALHOST: ${{ secrets.RABBITMQ_VIRTUALHOST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Restore cached SQL scripts
    - name: Restore SQL scripts from cache
      uses: actions/cache@v4
      with:
        path: deploy/sql/
        key: sql-scripts-${{ github.event.workflow_run.run_id }}

    - name: Replace secrets in Docker Compose
      shell: powershell
      run: |
        (Get-Content deploy/docker-compose.dev.yml) `
        -replace '@@SQLSERVER_SA_PASSWORD@@', "$env:SQLSERVER_SA_PASSWORD" `
        -replace '@@ORDERDB_CONNECTIONSTRING@@', "$env:ORDERDB_CONNECTIONSTRING" `
        -replace '@@INVENTORYDB_CONNECTIONSTRING@@', "$env:INVENTORYDB_CONNECTIONSTRING" `
        -replace '@@RABBITMQ_USERNAME@@', "$env:RABBITMQ_USERNAME" `
        -replace '@@RABBITMQ_PASSWORD@@', "$env:RABBITMQ_PASSWORD" `
        -replace '@@RABBITMQ_VIRTUALHOST@@', "$env:RABBITMQ_VIRTUALHOST" `
        | Set-Content deploy/docker-compose.dev.yml

    - name: Pull latest images
      run: |
        docker pull majidebadiparsajob/orderservice:latest
        docker pull majidebadiparsajob/inventoryservice:latest
        docker pull majidebadiparsajob/orderdb-migrator:latest
        docker pull majidebadiparsajob/inventorydb-migrator:latest

    - name: Clean previous containers
      run: docker-compose -f deploy/docker-compose.dev.yml down
      continue-on-error: true

    - name: Start infrastructure (DB + RabbitMQ)
      run: docker-compose -f deploy/docker-compose.dev.yml up -d sqlserver rabbitmq

    # Step 1: Wait until container created
    - name: Verify sqlserver-db container exists
      shell: powershell
      run: |
        Write-Host "Checking if container sqlserver-db exists..."
        for ($i = 1; $i -le 10; $i++) {
          $containerExists = docker ps -a --format "{{.Names}}" | Select-String "sqlserver-db"
          if ($containerExists) {
            Write-Host "Container sqlserver-db detected."
            break
          }
          else {
            Write-Host "Container not created yet. Waiting 2 seconds..."
            Start-Sleep -Seconds 2
          }
        }

    # Step 2: Wait for SQL Server inside container
    - name: Wait for SQL Server to be ready
      shell: powershell
      run: |
        Write-Host "Waiting for SQL Server to become ready..."
        for ($i = 1; $i -le 30; $i++) {
          try {
            docker run --rm --network host mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$env:SQLSERVER_SA_PASSWORD" -Q "SELECT 1"
            Write-Host "SQL Server is ready."
            break
          }
          catch {
            Write-Host "SQL Server not ready yet. Retrying in 2 seconds..."
            Start-Sleep -Seconds 2
          }
        }


    # Apply OrderDb SQL
    - name: Apply OrderDb SQL script
      shell: powershell
      run: |
        docker run --rm --network host -v ${env:GITHUB_WORKSPACE}\deploy\sql:/sql mcr.microsoft.com/mssql-tools `
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$env:SQLSERVER_SA_PASSWORD" -d master -i /sql/OrderDb.sql

    # Apply InventoryDb SQL
    - name: Apply InventoryDb SQL script
      shell: powershell
      run: |
        docker run --rm --network host -v ${env:GITHUB_WORKSPACE}\deploy\sql:/sql mcr.microsoft.com/mssql-tools `
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$env:SQLSERVER_SA_PASSWORD" -d master -i /sql/InventoryDb.sql

    - name: Deploy application services
      run: docker-compose -f deploy/docker-compose.dev.yml up -d orderservice inventoryservice
