name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    env:
      SQLSERVER_SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}
      ORDERDB_CONNECTIONSTRING: ${{ secrets.ORDERDB_CONNECTIONSTRING }}
      INVENTORYDB_CONNECTIONSTRING: ${{ secrets.INVENTORYDB_CONNECTIONSTRING }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USERNAME }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_VIRTUALHOST: ${{ secrets.RABBITMQ_VIRTUALHOST }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Replace secrets in Docker Compose
      run: |
        sed -i "s|@@SQLSERVER_SA_PASSWORD@@|${SQLSERVER_SA_PASSWORD}|g" deploy/docker-compose.production.yml
        sed -i "s|@@ORDERDB_CONNECTIONSTRING@@|${ORDERDB_CONNECTIONSTRING}|g" deploy/docker-compose.production.yml
        sed -i "s|@@INVENTORYDB_CONNECTIONSTRING@@|${INVENTORYDB_CONNECTIONSTRING}|g" deploy/docker-compose.production.yml
        sed -i "s|@@RABBITMQ_USERNAME@@|${RABBITMQ_USERNAME}|g" deploy/docker-compose.production.yml
        sed -i "s|@@RABBITMQ_PASSWORD@@|${RABBITMQ_PASSWORD}|g" deploy/docker-compose.production.yml
        sed -i "s|@@RABBITMQ_VIRTUALHOST@@|${RABBITMQ_VIRTUALHOST}|g" deploy/docker-compose.production.yml

    - name: Pull latest images
      run: docker-compose -f deploy/docker-compose.production.yml pull

    - name: Clean previous containers
      run: docker-compose -f deploy/docker-compose.production.yml down || true

    - name: Start infrastructure
      run: docker-compose -f deploy/docker-compose.production.yml up -d

    - name: Apply SQL Migrations
      run: bash deploy/run-migrations.sh

    - name: Deploy application services
      run: docker-compose -f deploy/docker-compose.production.yml up -d orderservice inventoryservice
