name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Docker Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest OrderService image
      run: docker pull majidebadiparsajob/orderservice:latest

    - name: Pull latest InventoryService image
      run: docker pull majidebadiparsajob/inventoryservice:latest

    - name: Docker Compose Pull
      run: docker-compose -f deploy/docker-compose.dev.yml pull

    - name: Deploy using docker-compose
      run: docker-compose -f deploy/docker-compose.dev.yml up -d

    - name: Wait for containers
      run: sleep 10

    - name: Verify containers
      run: docker ps
