name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: dev

    env:
      SQLSERVER_SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Secrets in Docker Compose
        shell: powershell
        run: |
          (Get-Content docker-compose.yml) `
          -replace '@@SQLSERVER_SA_PASSWORD@@', "$env:SQLSERVER_SA_PASSWORD" `
          | Set-Content docker-compose.yml

      - name: Clean previous containers
        run: docker-compose -f docker-compose.yml down
        continue-on-error: true

      - name: Start Infrastructure (SQLServer + RabbitMQ)
        run: docker-compose -f docker-compose.yml up -d sqlserver rabbitmq

      - name: Wait for SQL Server
        shell: pwsh
        run: |
          Write-Host "Waiting for SQL Server..."
          for ($i = 1; $i -le 30; $i++) {
            try {
              docker exec $(docker ps -qf "name=sqlserver-db") /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $env:SQLSERVER_SA_PASSWORD -Q "SELECT 1"
              Write-Host "SQL Server is ready."
              break
            }
            catch {
              Start-Sleep -Seconds 2
            }
          }

      - name: Run Database Migrations
        run: |
          docker-compose -f docker-compose.yml up order-db-migrator inventory-db-migrator

      - name: Start Services
        run: docker-compose -f docker-compose.yml up -d orderserviceapi inventoryserviceapi
