name: Deploy to Dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest OrderService image
      run: docker pull majidebadiparsajob/orderservice:latest

    - name: Pull latest InventoryService image
      run: docker pull majidebadiparsajob/inventoryservice:latest

    - name: Deploy using docker-compose
      run: docker-compose -f deploy/docker-compose.dev.yml up -d
