name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download SQL scripts artifact
      uses: actions/download-artifact@v4
      with:
        name: sql-scripts
        path: deploy/sql/

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push OrderService
      run: |
        docker build -t majidebadiparsajob/orderservice:latest -f OrderService/OrderService.API/Dockerfile .
        docker push majidebadiparsajob/orderservice:latest

    - name: Build and push InventoryService
      run: |
        docker build -t majidebadiparsajob/inventoryservice:latest -f InventoryService/InventoryService.API/Dockerfile .
        docker push majidebadiparsajob/inventoryservice:latest

    - name: Build and push OrderDb Migrator
      run: |
        docker build -t majidebadiparsajob/orderdb-migrator:latest -f OrderService/OrderService.API/MigrationDockerfile .
        docker push majidebadiparsajob/orderdb-migrator:latest

    - name: Build and push InventoryDb Migrator
      run: |
        docker build -t majidebadiparsajob/inventorydb-migrator:latest -f InventoryService/InventoryService.API/MigrationDockerfile .
        docker push majidebadiparsajob/inventorydb-migrator:latest
