name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push OrderService
      run: |
        docker build -t majidebadiparsajob/orderservice:latest -t majidebadiparsajob/orderservice:${{ env.sha_short }} -f OrderService/OrderService.API/Dockerfile .
        docker push majidebadiparsajob/orderservice:latest
        docker push majidebadiparsajob/orderservice:${{ env.sha_short }}

    - name: Build and Push InventoryService
      run: |
        docker build -t majidebadiparsajob/inventoryservice:latest -t majidebadiparsajob/inventoryservice:${{ env.sha_short }} -f InventoryService/InventoryService.API/Dockerfile .
        docker push majidebadiparsajob/inventoryservice:latest
        docker push majidebadiparsajob/inventoryservice:${{ env.sha_short }}

    - name: Build and Push OrderDb Migrator
      run: |
        docker build -t majidebadiparsajob/orderdb-migrator:latest -t majidebadiparsajob/orderdb-migrator:${{ env.sha_short }} -f OrderService/OrderService.API/MigrationDockerfile .
        docker push majidebadiparsajob/orderdb-migrator:latest
        docker push majidebadiparsajob/orderdb-migrator:${{ env.sha_short }}

    - name: Build and Push InventoryDb Migrator
      run: |
        docker build -t majidebadiparsajob/inventorydb-migrator:latest -t majidebadiparsajob/inventorydb-migrator:${{ env.sha_short }} -f InventoryService/InventoryService.API/MigrationDockerfile .
        docker push majidebadiparsajob/inventorydb-migrator:latest
        docker push majidebadiparsajob/inventorydb-migrator:${{ env.sha_short }}
