name: Docker Build

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-docker-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build OrderService Image
      run: docker build -t myeshop/orderservice:latest -f OrderService/OrderService.API/Dockerfile ./OrderService/OrderService.API

    - name: Build InventoryService Image
      run: docker build -t myeshop/inventoryservice:latest -f InventoryService/InventoryService.API/Dockerfile ./InventoryService/InventoryService.API

    - name: Build OrderDb Migrator Image
      run: docker build -t myeshop/orderdb-migrator:latest -f OrderService/OrderService.API/MigrationDockerfile ./OrderService/OrderService.API

    - name: Build InventoryDb Migrator Image
      run: docker build -t myeshop/inventorydb-migrator:latest -f InventoryService/InventoryService.API/MigrationDockerfile ./InventoryService/InventoryService.API
