name: Docker Build and Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-and-push-docker-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Generate OrderService SQL Migration Script
    - name: Generate OrderService Migration SQL
      run: |
        dotnet ef migrations script \
          --project OrderService/OrderService.Infrastructure/OrderService.Infrastructure.csproj \
          --startup-project OrderService/OrderService.API/OrderService.API.csproj \
          --context OrderDbContext \
          --output deploy/sql/orderdb-migration.sql \
          --idempotent

    # Generate InventoryService SQL Migration Script
    - name: Generate InventoryService Migration SQL
      run: |
        dotnet ef migrations script \
          --project InventoryService/InventoryService.Infrastructure/InventoryService.Infrastructure.csproj \
          --startup-project InventoryService/InventoryService.API/InventoryService.API.csproj \
          --context InventoryDbContext \
          --output deploy/sql/inventorydb-migration.sql \
          --idempotent

    # Build and Tag Docker Images
    - name: Build and Push Docker Images
      run: |
        docker build -t majidebadiparsajob/orderservice:latest -f OrderService/OrderService.API/Dockerfile .
        docker build -t majidebadiparsajob/inventoryservice:latest -f InventoryService/InventoryService.API/Dockerfile .
        docker build -t majidebadiparsajob/orderdb-migrator:latest -f OrderService/OrderService.API/MigrationDockerfile .
        docker build -t majidebadiparsajob/inventorydb-migrator:latest -f InventoryService/InventoryService.API/MigrationDockerfile .

        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

        docker push majidebadiparsajob/orderservice:latest
        docker push majidebadiparsajob/inventoryservice:latest
        docker push majidebadiparsajob/orderdb-migrator:latest
        docker push majidebadiparsajob/inventorydb-migrator:latest
