name: Docker Build

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build OrderService Image
      run: docker build -t myeshop/orderservice:latest -f OrderService/OrderService.API/Dockerfile .

    - name: Build InventoryService Image
      run: docker build -t myeshop/inventoryservice:latest -f InventoryService/InventoryService.API/Dockerfile .
