name: InventoryService - Docker Publish

on:
  push:
    branches: [ "main" ]
    paths:
      - 'InventoryService/**'
      - '.github/workflows/inventoryservice-docker-publish.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: meta
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: InventoryService/InventoryService.API/Dockerfile
          push: true
          tags: |
            majidebadiparsajob/inventoryservice:sha-${{ steps.meta.outputs.sha_short }}
            majidebadiparsajob/inventoryservice:latest
          cache-from: type=registry,ref=majidebadiparsajob/inventoryservice:latest
          cache-to: type=inline
